### ISSUE TITLE
[Bug]: Item Duplication with Carpet rule stackableShulkerBoxes

### ISSUE THREAD

**Issue by mrniddala** [Fuzss/easyshulkerboxes#1]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19

### Mod Version (Required)

Newest

### Notes (Required)

Hello, I was playing right now with the mod and see that I can easy duplicate my items this way. I hope you can fix that.
Greetings.

**Comment by Fuzss** [comment]
Good point, fixed in v4.0.2. Thanks for reporting!
