### ISSUE TITLE
[Bug]: Version 4.3.6 cause Minecraft Client to failed startup

### ISSUE THREAD

**Issue by hipsterjazzbo** [Fuzss/easyshulkerboxes#14]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.3.6

### Notes (Required)

I'm not sure what exactly is happening, as the client crashes without ever showing a window or leaving any error logs. Let me know if I can provide anything useful :)

Rolling back to 4.3.5 again allows the client to start correctly.

**Comment by Fuzss** [comment]
Thanks for reporting, fixed in v4.3.7.
