### ISSUE TITLE
[Bug]: Breaks the mouse drag feature from Mouse Tweaks

### ISSUE THREAD

**Issue by Moecchiato** [Fuzss/easyshulkerboxes#16]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.3.7

### Notes (Required)

When Easy Shulker Box and Mouse Tweaks are installed together Mouse Tweaks is no longer able to drag items into any inventory.

**Comment by Fuzss** [comment]
Thanks for reporting! Fix will be part of v4.4.0, will be out in a few days, still finishing up other features in the new version.

**Comment by ginsm** [comment]
Has there been any progress on this? Love the mod and it's hard to choose between Mouse Tweaks' drag functionality and this mod's functionality.

**Comment by Fuzss** [comment]
v4.4.0 is finally live now, fixing this.
