### ISSUE TITLE
[Suggestion]: Compat with Obscure Tooltips

### ISSUE THREAD

**Issue by murao-kun** [Fuzss/easyshulkerboxes#17]
### Suggestion (Required)

Mod link: https://www.curseforge.com/minecraft/mc-mods/obscure-tooltips
For now both mods are working together, but tooltips looking offset as also selected item icon not rendering.

**Comment by Fuzss** [comment]
Please post a screenshot so I can see what’s wrong.

**Comment by murao-kun** [comment]
![Uploading image-1.png…]()

**Comment by murao-kun** [comment]
![image](https://user-images.githubusercontent.com/110398598/205811183-97f76e15-3b51-4f9a-87a0-ab4449648689.png)

**Comment by Fuzss** [comment]
I see, thank you. That mod is closed source unfortunately, so I can‘t easily look into this. It‘s probably best to talk to the author first.

**Comment by Fuzss** [comment]
I added some code so Easy Shulker Boxes will no longer render the additional tooltip if not enough space is available. I think this is the most I can try to do for this, otherwise I can only recommend deactivating selected item tooltips in the config.
