### ISSUE TITLE
[Suggestion]: {Bug}: Configure the number of slots Bundles can have {or fix compat with mods that increase it, like More Bundles}

### ISSUE THREAD

**Issue by Reshirou** [Fuzss/easyshulkerboxes#18]
### Suggestion (Required)

With More Bundles and Bundle slots set to 128, Bundles still cap at 64 despite showing up as half filled.
This is, of course, only with the Bundle function turned on from Easy Shulker Boxes. When turned off, 128 slots works normally again.

I figure adding the functionality to configure slots in Easy Shulker Boxes is probably easier than adding dedicated compatibility, but I wouldn't know for sure

I am aware of Bag of Holding, but the functionality of Bags are just not the same as Bundles

**Comment by Fuzss** [comment]
As of v4.0.0 Easy Shulker Boxes only affects vanilla bundles. But you yourself can add support for bundles from other mods via a data pack.

Here is the default file for the vanilla bundle supplied by Easy Shulker Boxes: https://github.com/Fuzss/easyshulkerboxes/blob/1.19/Forge/src/generated/resources/data/minecraft/item_container_providers/bundle.json
Here is the documentation for that: https://github.com/Fuzss/easyshulkerboxes#item-provider-type-easyshulkerboxesbundle
