### ISSUE TITLE
[Bug]: Mod breaks bundle functionality 

### ISSUE THREAD

**Issue by Wash113** [Fuzss/easyshulkerboxes#19]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.3.7

### Notes (Required)

Bundles are deleting held items when you place them back into your inventory. The error in the server's log is related to this mod. Ive listed the error below. The error in question starts at line 435

### latest.log (Optional)

https://gist.github.com/Wash113/9df23171264509f01bc59989f18f25d2

**Comment by Leronus** [comment]
This bug is still present unfortunately

**Comment by Leronus** [comment]
Only on servers it appears

Error log: 

https://gist.github.com/Leronus/d1744395358648d96237c4970f439967

**Comment by getBoolean** [comment]
> Only on servers it appears
> 
> Error log:
> 
> https://gist.github.com/Leronus/d1744395358648d96237c4970f439967

I think this is a different but related issue.

**Comment by Fuzss** [comment]
Fixed in v4.4.0.
