### ISSUE TITLE
[Crash]: Crash when hovering Shulkerbox with content inside.

### ISSUE THREAD

**Issue by ardissaps** [Fuzss/easyshulkerboxes#2]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

Latest

### Notes (Required)

Crash when hovering ShulkerBox with content inside if [Shetiphian Core](https://www.curseforge.com/minecraft/mc-mods/shetiphiancore) installed.
https://github.com/ShetiPhian/Localizations-and-Issues/issues/362

### Crash Report (Required)

https://paste.atlauncher.com/view/38f8c98f-3cba-4ebf-badd-e3c725db40f4

**Comment by ardissaps** [comment]
Fixed the issue by disabling certain setting on the config of Shetiphian Core, idk if it will cause problem but it works now.
![image](https://user-images.githubusercontent.com/82106625/180582072-bca7760b-504c-4161-a491-7e7dce7c5b0b.png)

**Comment by Fuzss** [comment]
Thanks for the report, that's on the other mod though. If Fabric API has a hook there to support custom tooltip data you really can't just ignore that and let the game crash.
