### ISSUE TITLE
[Suggestion]: Small tweak to the "+"

### ISSUE THREAD

**Issue by SebSemos** [Fuzss/easyshulkerboxes#20]
### Suggestion (Required)

I think it could be cool to have two colors for the + sign when we hold an item. One would be for any container that has space as now, and the other for container where there is space and the item is already present.
Possibly another symbol if there is a container with the item but no space, but I don't see a big utility for this case...

**Comment by Fuzss** [comment]
Thanks a lot for your suggestion, I like it a lot! This has been added in v4.4.0. A green indicator will show when the item is already present, a red one will appear when the item is present, but there is no more space to add more of it.
I agree that the red indicator isn't too useful, but it was just one more line of code as the implementation itself already support that anyways, so I enabled it.
