### ISSUE TITLE
[Bug]: Compat with reinforced shulker boxes

### ISSUE THREAD

**Issue by DanMeadWasTaken** [Fuzss/easyshulkerboxes#21]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.3.7

### Notes (Required)

It states in the main page that the mod comes with built-in support for [Reinforced Shulker Boxes](https://www.curseforge.com/minecraft/mc-mods/reinforced-shulker-boxes) except when I try to use it's functions on any of the shulker boxes from that mod, it simply doesn't register it.

**Comment by Fuzss** [comment]
The readme reflect v4.4.0, the latest public version is v4.3.7 though. Just haven't gotten around to release the new version.

**Comment by DanMeadWasTaken** [comment]
Alright, is there some way for me to get a hold of that version myself? or do should i just wait for you to release it?

**Comment by DanMeadWasTaken** [comment]
Closing this as it wasn't a bug, just a lack of update. thank you for the awesome mod btw

**Comment by Fuzss** [comment]
Thanks!

Just hit me up on our discord, I'll compile the latest version and send it to you there: https://lunapixel.studio/discord
