### ISSUE TITLE
[Crash]: Incompat with Scout

### ISSUE THREAD

**Issue by DanMeadWasTaken** [Fuzss/easyshulkerboxes#22]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.4.0

### Notes (Required)

When hovering over a reinforced shulkerbox or normal shulkerbox while it's in a scout inventory slot, game crashes. 

### Crash Report (Required)

https://mclo.gs/FCumaMT

**Comment by Fuzss** [comment]
Thanks! Bugfix release is on the Discord.
