### ISSUE TITLE
[Bug]: Ender Chest does not have functionality

### ISSUE THREAD

**Issue by Thedeur** [Fuzss/easyshulkerboxes#25]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

3.1.1

### Notes (Required)

"...And believe it or not, this works with Ender Chests, too!"

I'm assuming the Ender Chest works similarly to the Shulker Boxes in this mod, but when I right-click with either an item or the Ender Chest itself over an item, it just does the default vanilla swap. I looked in the configs too, which didn't have anything. I'm running only this mod with its library mod. 

Forge 40.2.0
Puzzles Lib 3.3.5

**Comment by Fuzss** [comment]
That feature is in the 1.19 version only.
