### ISSUE TITLE
[Suggestion]: Extract only one item

### ISSUE THREAD

**Issue by SebSemos** [Fuzss/easyshulkerboxes#26]
### Suggestion (Required)

When you have a full stack of item in a shulker you might sometime only want a few of them. 
A combinaison of "CTRL right click" could give you only one instead of the full stack.

**Comment by Fuzss** [comment]
Thanks a lot for the suggestion, this is really great! I went even further in v4.4.0 and added something I call "precision mode": 
- Hold `Ctrl` (or `Cmd`) and right-click to extract a single item
- Hold `Ctrl` (or `Cmd`) and left-click to insert a single item (adding it back, this overrides picking up/swapping the container item while the additional key is held)
- Hold `Ctrl` (or `Cmd`) and scroll up or down to quickly extract / insert multiple items (overrides scrolling between the slots in the container item while the additional key is held)
- This also works with the dragging feature, so while holding `Ctrl` (or `Cmd`) you'll only insert / extract single items from stacks.

There is also another new feature related to all this which always shows a container items tooltip (when it is carried by the cursor or when another item is held above it by the cursor) while the `Alt` key is pressed.
All modifier keys required to be held are fully configurable.

I'd love to hear what you think of this implementation and if you have any more suggestions! We also have a Discord server where it's much easier to talk if you want, here is a link (find me in `#fuzs-projects`): https://lunapixel.studio/discord
