### ISSUE TITLE
[Crash]: Server Crash With Bundles

### ISSUE THREAD

**Issue by getBoolean** [Fuzss/easyshulkerboxes#27]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.3.7

### Notes (Required)

Place item into bundle from the inventory. Server crashes immediately.

I placed coal ore, and one of the players on my server had it happen with gold ore. Likely isn't related to the block type.

### Crash Report (Required)

https://crashy.net/7291c4c9-8498-4548-8a8c-58d2cd85dac5

https://gist.github.com/getBoolean/b54a4356bad54b992105cb02e34ee96a

**Comment by Fuzss** [comment]
Same as #19.
