### ISSUE TITLE
[Suggestion]: Toggle to disable item inserting in Backpacked backpacks.

### ISSUE THREAD

**Issue by murao-kun** [Fuzss/easyshulkerboxes#28]
### Suggestion (Required)

You can abuse backpacked mod with that mod installed. Would be good to disable item inserting in it with config option.

By default you can't unquip backpack that have items in it. This thing balance the mod to force the player to carry only one backapack on you, to make a real difference with shulker boxes. But with this mod installed you can insert items right in your inventory, that breaking this mod balance.

This config option is enabled by default. So the asked one option should be default one too.
![image](https://github.com/Fuzss/easyshulkerboxes/assets/110398598/99e4aa20-0339-4522-a24d-446764dc859f)

**Comment by Fuzss** [comment]
I see, I forgot about that option. I removed Backpacked integration for now, it's a bit tricky with the custom backpack slot / curios slot to properly detect that. Whoever plays with that option disabled can just manually add integration back with a data pack.

**Comment by murao-kun** [comment]
Thanks! This is the option that come in the mod by default, so most of the players plays with it. But I guess after all you are not really need that type of integration. In the future, would be cool to have configurable option on your side, to only view contents of some items, instead of also grabbing. That would solve that and be amazing qol addition to the mod.
