### ISSUE TITLE
[Bug]: Not working when joined LAN world

### ISSUE THREAD

**Issue by suddenallon** [Fuzss/easyshulkerboxes#33]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

Working in singleplayer world, but when joined a friend's LAN world, not working anymore
Tested - Shulker boxes and bundles

**Comment by Fuzss** [comment]
Fixed in v8.0.2.
