### ISSUE TITLE
[Suggestion]: Better support for enderchests of different sizes

### ISSUE THREAD

**Issue by T0mt4ru** [Fuzss/easyshulkerboxes#35]
### Suggestion (Required)

Hello,

I'm using "Easy Shulkerboxes" in combination with "Iron ender chests".
The [Item Provider Type: easyshulkerboxes:ender_chest] however, does not have any options to change the size of the displayed inventory.

Is it possible to implement inventory_height and inventory_width for enderchests as well?

**Comment by Fuzss** [comment]
The mod you mentioned is ARR and closed source, therefore no support is planned.
