### ISSUE TITLE
[Suggestion]: Support for removing/disabling container providers without log spam

### ISSUE THREAD

**Issue by mosharky** [Fuzss/easyshulkerboxes#36]
Currently, I'm just overriding the json files with empty jsons, but it would be nice to have something like `type: "forge:none"` to override them without log spam.

**Comment by katubug** [comment]
I would really like this, too. Ideally a config would be great, but I'm happy doing it via datapack if that's easier for you.

**Comment by Fuzss** [comment]
This is already possible via the filter section in `pack.mcmeta`: https://minecraft.wiki/w/Data_pack#pack.mcmeta

As an alternative in 1.20.4+ a new type has been added to achieve your desired behavior: `iteminteractions:none`.
