### ISSUE TITLE
[Suggestion]: Configurable key binds

### ISSUE THREAD

**Issue by AdamBrezik** [Fuzss/easyshulkerboxes#39]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

My scrolling controls are being blocked by another conflicting key bind like in my case. This could be prevented by Mouse Wheelie mod including compatibility, but it makes more sense to add configurable key binds on Easy Shulker Boxes side, as it is quite common trick how to prevent such situations. Also I think it'd be easier to implement and I deem it a more realistic suggestion.

**Comment by Fuzss** [comment]
there are already config options for the required modifier keys. Look at the `iteminteractions-client-toml` config, `selected_item_tooltips` and `precision_mode` should be what you are looking for

**Comment by Fuzss** [comment]
For the scrolling itself Fabric Api has common events for hooking into the mouse scrolling on a screen. If another mod does not use those events it won't be compatible, as seems to be the case for Mouse Wheelie.

As a workaround holding the `Alt` while scrolling seems to allow the Easy Shulker Boxes behavior to work without Mouse Wheelie interfering.
