### ISSUE TITLE
[Crash]: Crash with newest PuzzlesLib version

### ISSUE THREAD

**Issue by mrniddala** [Fuzss/easyshulkerboxes#4]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

Latest

### Notes (Required)

Hello, I've tried to update the mod but it doesn't work.

### Crash Report (Required)

https://pastebin.com/raw/hxYT3dGk

**Comment by Fuzss** [comment]
Fixed in v4.3.0.
