### ISSUE TITLE
[Bug]: Mouse Tweaks incompat

### ISSUE THREAD

**Issue by bubin7766** [Fuzss/easyshulkerboxes#40]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.1

### Notes (Required)

When using Easy Shulker Boxes with Mouse Tweaks if you right click and drag over items with RMB it spits back out the initial item instead of leaving it inside the box/bundle. But disabling the RMB Tweak setting for mouse tweaks fixes this.
Not sure if this was something i needed to bring up here or in mouse tweaks but I just wanted to make it known for maybe a possible fix on your end?

**Comment by bubin7766** [comment]
I've found out something interesting after some more testing, If you install Metal Bundles alongside Easy Shulker Boxes and Mouse Tweaks it actually fixes the issue mentioned above! Maybe you could implement the solution used for Metal Bundles into Easy Shulker Boxes to fix it for those who don't install Metal Bundles?

**Comment by bubin7766** [comment]
And this will be unrelated but would it be possible to add compatibility with the Sophisticated Storage mod on CurseForge?
I double checked to be sure but there does not seem to be any native functionality from their end to have the same shulker box utility your mod adds.

**Comment by Fuzss** [comment]
Easy Shulker Boxes uses Forge / Fabric events everywhere for the new interactions, if other mods do not use those events or ignore them there is nothing I will do about it, that's up to those mods.

For Sophisticated Storage see #42.
