### ISSUE TITLE
[Bug]: Vanilla server tool tip bug

### ISSUE THREAD

**Issue by Quantum-mutnauQ** [Fuzss/easyshulkerboxes#41]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.1

### Notes (Required)

Forge: 47.2.20
Puzzles Api: 8.1.4
Puzzles Access Api: 8.0.7
Puzzles Lib: 8.1.17

If I join a Vanilla(Paper server) server and with the mod I display the tool tip from your schulckerbox, then the items and the complete box are not shown. When I was on a Forge server with the mod, then the items and the box are correctly shown on the Vanilla server.  

Before visit Forge server on Vanilla server
![grafik](https://github.com/Fuzss/easyshulkerboxes/assets/141065355/d9872b1f-9da1-4e58-9eb7-a6ee8da8670a)

After visit Forge server on Vanilla server:
![grafik](https://github.com/Fuzss/easyshulkerboxes/assets/141065355/dee93372-7b3d-4148-a22b-eeccb82e4123)

**Comment by Fuzss** [comment]
The mod must be installed on both the client & server to work.
In your case there are leftover configurations from the Forge server still present, those are cleared now in v20.4.2.

**Comment by Quantum-mutnauQ** [comment]
Hello,
I would be nice if you add that It is displaying the toll tip in the right way. It is very confusing when the shulkerbox seams like it is empty but it is full.

**Comment by Fuzss** [comment]
Fixed in v20.4.3. The vanilla tooltip will show when on a server without the mod.

**Comment by Quantum-mutnauQ** [comment]
Thanks for dooind this, is this update able for 1.20.1(forge)?
