### ISSUE TITLE
[Bug]: Config editing command doesn't work

### ISSUE THREAD

**Issue by sternschnaube** [Fuzss/easyshulkerboxes#44]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

v20.4.0

### Minimal Setup (Required)

Yes

### Notes (Required)

The command "/config showfile <modid>" doesn't works.
And I can't spot the config file - there must be a config file, or not?

Mod Menu support would be really appreciated. Thanks for the 1.20.4 update :party

### latest.log (Required)

/

**Comment by Fuzss** [comment]
The command has changed to ˋ/neoforgeconfigˋ in 1.20.4. But keep in mind that most of the mod is controlled via a data pack. Also for Mod Menu Support you can use Forge Config Screens when it updates for 1.20.4.

**Comment by sternschnaube** [comment]
Thanks for the fast answer!!
FAQ should be updated on Modrinth 😊 

![image](https://github.com/Fuzss/easyshulkerboxes/assets/120551916/2c072fe4-07c1-4ca9-bd91-c63df25e3e1e)

**Comment by wilebaldo** [comment]
> Thanks for the fast answer!! FAQ should be updated on Modrinth 😊
> 
> ![image](https://private-user-images.githubusercontent.com/120551916/307513977-2c072fe4-07c1-4ca9-bd91-c63df25e3e1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NzgzNTYsIm5iZiI6MTcxMTY3ODA1NiwicGF0aCI6Ii8xMjA1NTE5MTYvMzA3NTEzOTc3LTJjMDcyZmU0LTA3YzEtNGNhOS1iZDkxLWM2M2RmMjVlM2UxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQwMjA3MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmRhNjRhNGIyYWQwNDU3ZGEzMjg0MDllYjNmNTkzYzQyYzM3OGZkNjE1ZjVhNWY2N2IxNzhkMzI5MjIzM2E4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ljrVbCR8SvdTQHlC0jdtm8c9ihZ85bzI5pJM-vGicu4)

yes, You must to change the configuration FAQ with the new information.
