### ISSUE TITLE
[Suggestion]: width and height configurable

### ISSUE THREAD

**Issue by peow** [Fuzss/easyshulkerboxes#45]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.1

### Mod Version(s) (Optional)

v8.0.2

### Suggestion (Required)

i used Carpet mod to double the size of the Ender Chest, however the Easy Shulker Boxes mod still shows the Ender Chest in the standard size, I even tried to modify it within the .jar but it still show the same thing
![image](https://github.com/Fuzss/easyshulkerboxes/assets/105888751/36455ce6-7c1c-4e5c-b672-12ca2c42178c)
![image](https://github.com/Fuzss/easyshulkerboxes/assets/105888751/5ccb6f3b-a50e-414c-bd79-4941e8fa3fc8)
![image](https://github.com/Fuzss/easyshulkerboxes/assets/105888751/d540677f-1dd0-4ca9-a85a-7382e178fb36)

**Comment by Fuzss** [comment]
See #32.
