### ISSUE TITLE
[Crash]: item interactions crashes my game which is embedded in this

### ISSUE THREAD

**Issue by ooogerman** [Fuzss/easyshulkerboxes#48]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

20.45

### Minimal Setup

No

### Notes (Required)

launch game
game crashes
item interactions is the culprit

### Crash Report (Required)

https://gist.github.com/ooogerman/82868393705af35f8d3bbbbb6376f8e6

**Comment by Fuzss** [comment]
Thanks, fixed in v20.4.6.

**Comment by ooogerman** [comment]
when will it be released?
