### ISSUE TITLE
[Suggestion]: Option to disable Tooltip

### ISSUE THREAD

**Issue by sternschnaube** [Fuzss/easyshulkerboxes#49]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.4

### Mod Version(s) (Optional)

EasyShulkerBoxes-v20.4.6

### Suggestion (Required)

I would like to use the tooltip from Shulker Box Tooltip, but your mod prioritizes the tooltip over it.
A new config option to disable would be great.

**Comment by Fuzss** [comment]
Change the reveal_contents client option to require a modifier key, which will disable the tooltip by default. But please note that most features like tooltip scrolling will no longer work as they require the tooltip.

**Comment by sternschnaube** [comment]
Good to know, thanks 😊

**Comment by sternschnaube** [comment]
It doesn't work this way.

![image](https://github.com/Fuzss/easyshulkerboxes/assets/120551916/b5488b35-2bd7-47da-a8b6-8446ad5ca5e6)

**Comment by Fuzss** [comment]
Easy Shulker Boxes does not include an option to disable the tooltip as it is essential for almost all parts of the mod. If you prefer the tooltip from another mod uninstall Easy Shulker Boxes.

**Comment by sternschnaube** [comment]
Hoped for a better answer 😂
But thanks!
