### ISSUE TITLE
Cardinal Component API no longer embedded

### ISSUE THREAD

**Issue by mrniddala** [Fuzss/easyshulkerboxes#5]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

Latest

### Notes (Required)

[main/INFO]: Fix: add [add:cardinal-components-block 1 ([(-∞,∞)]), add:cardinal-components-chunk 1 ([(-∞,∞)]), add:cardinal-components-world 1 ([(-∞,∞)])], remove [], replace []
[22:36:35] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install cardinal-components-block, any version.
	 - Install cardinal-components-chunk, any version.
	 - Install cardinal-components-world, any version.
Unmet dependency listing:
	 - Mod 'Easy Shulker Boxes' (easyshulkerboxes) 4.3.0 requires any version of cardinal-components-block, which is missing!
	 - Mod 'Easy Shulker Boxes' (easyshulkerboxes) 4.3.0 requires any version of cardinal-components-chunk, which is missing!
	 - Mod 'Easy Shulker Boxes' (easyshulkerboxes) 4.3.0 requires any version of cardinal-components-world, which is missing!
	 - Mod 'Statement Vanilla Compatibility Module' (statement_vanilla_compatibility) 1.0.1+1.14.4-1.15.2 requires any version between 1.14.0-0 (inclusive) and 1.16.0-0 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.14' (viafabric-mc114) 0.4.8+17-main requires any 1.14.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.15' (viafabric-mc115) 0.4.8+17-main requires any 1.15.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.16' (viafabric-mc116) 0.4.8+17-main requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.17' (viafabric-mc117) 0.4.8+17-main requires any 1.17.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	 - Mod 'ViaFabric for 1.18' (viafabric-mc118) 0.4.8+17-main requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [minecraft_server.jar:0.11.0]

I was downloading the Cardinal Component API and it works now. 
You should change the flag on Modrinth:

![image](https://user-images.githubusercontent.com/75373609/185813882-d3c0b167-9d34-4b6a-b2fd-0eac28be4182.png)

### Crash Report (Required)

/

**Comment by Fuzss** [comment]
That's intentional, Cardinal Components is now a dependency that needs to be separately downloaded.
The flag on Modrinth is set to required instead of embedded which reflects that.
