### ISSUE TITLE
[Bug]: Easy Shulker Boxes mod issue

### ISSUE THREAD

**Issue by JulioAlvarez15** [Fuzss/easyshulkerboxes#50]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.0.2

### Minimal Setup (Required)

Yes

### Notes (Required)

It just that every time I put my cursor on the shulker box it shows three tool tips (Or inventory menus). I think it might be the Quark mod, but idk honestly
![2024-05-01_14 25 24](https://github.com/Fuzss/easyshulkerboxes/assets/160561010/fd5b37f6-9beb-4a4d-a086-d93e491a418d)

### latest.log (Required)

https://gist.github.com/JulioAlvarez15/c074b9787dcce3831915c6cff9362d1e

**Comment by Fuzss** [comment]
Yeah you have multiple mods that add the tooltip contents. Easy Shulker Boxes adds the one with the thick border.

**Comment by Fuzss** [comment]
This can be solved by disabling the tooltips from the other mods. Easy Shulker Boxes does not include an option to disable the tooltip as it is essential for almost all parts of the mod.
