### ISSUE TITLE
[Crash]: Possible incompatibility with Friends and Foes or Bedrockify

### ISSUE THREAD

**Issue by Wash113** [Fuzss/easyshulkerboxes#54]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

21.0.1

### Minimal Setup

No

### Notes (Required)

So this is a weird one. I was messing around on my server and ran into a Rascal from Additional Additions. I played his game, and at the end he tossed me a bundle. Upon the bundle entering my inventory, my game crashed. Im honestly not sure if the problem lies within this mod, but the crash log says the issue occurred in the fuzs.iteminteractions class. There is also a reference to Bedrockify, so that could be a problem too. Honestly not sure. Happy Hunting!

### Crash Report (Required)

https://mclo.gs/TDamJmh

### latest.log (Optional)

https://mclo.gs/AfhIoRJ

**Comment by Fuzss** [comment]
Report this to Bedrockify, the issue lies here: https://github.com/juancarloscp52/BedrockIfy/blob/d24a44d75c0525906e0caa0bd15e3c2ed0da5958/src/main/java/me/juancarloscp52/bedrockify/client/features/heldItemTooltips/HeldItemTooltips.java#L115

**Comment by Wash113** [comment]
Sounds good, thanks for looking into it!
