### ISSUE TITLE
[Suggestion]: How do I disable bundle interaction?

### ISSUE THREAD

**Issue by FaeWulf** [Fuzss/easyshulkerboxes#55]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.21

### Suggestion (Required)

I am making a mod that adds more capacity for vanilla bundle,. when using with this mod it doesn't work as intend (this mod prevent adding more items than 64)
Is there any way to work around this?

**Comment by Fuzss** [comment]
There is a provider type `iteminteractions:empty` that allows for disabling an existing provider.

So in your mod you can include [this file](https://github.com/Fuzss/easyshulkerboxes/blob/main/1.21/Common/src/generated/resources/data/easyshulkerboxes/item_contents_provider/bundle.json) with
```json

{
  "type": "iteminteractions:empty"
}
```.

At least that's the idea, there might be an issue with mod data pack loading order, when your mod loads after mine it's likely not going to work.

**Comment by FaeWulf** [comment]
Thank you!
