### ISSUE TITLE
[Bug]: Prevents logging onto remote server, while previous versions didn't.

### ISSUE THREAD

**Issue by Jill-Kitten** [Fuzss/easyshulkerboxes#56]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

EasyShulkerBoxes-v21.0.2-1.21-NeoForge

### Minimal Setup (Required)

Yes

### Notes (Required)

On previous versions using EasyShulkerBoxes with Forge on Realms had limited functionality [I am sure due to not having access to the server side], but it did not prevent you from using the Realm, this latest version kills the ability to use Realms giving the "Connection Lost" warning as in the supplied image preventing the use of Realms [and likely other servers where you cannot get access to the server side].

I already went to NeoForge with this issue, they found the offending file to be EasyShulkerBoxes, and they sugested I come here to see if I cen get this resolved..  Other mods work without having to remove them every time you go on Realms, like AppleSkin, Journeymap, and WorldEdit [and previously EasyShulkerBoxes] all work on it, but WorldEdit has very limited functionality because of the limitations of not having access to the server side, but it still has some functionality, and it doesn't kill your ability to use the server.

Now I am assuming this is a bug considering it didn't do this in previous versions and typically when a mod encounters a server it can't use, it would typically disable itself, not prevent you from entering the server, it is a basic common programmer's paradigm called Graceful Degradation.  You don't halt the whole system because you don't have everything you want/need, or like what they use, you reduce functionality, give a warning, and log the issue, you don't kill everything, so again I assume this is a bug.

Also note that the dependent library mods Puzzles & ForgeConfigApiPort do not cause the issue, with them installed and the EasyShulkerBoxes file removed I can get on Realms without issue, only when I include the fie for EasyShulkerBoxes does it cause this issue.

![EasyShulkerBoxes prevents using Realms](https://github.com/user-attachments/assets/00787990-b443-48b7-b77a-af8ad0ed9d04)

### latest.log (Required)

https://gist.github.com/NeoCamelot/60ab42c96f2f1ac5d94486ecd4fbad51

**Comment by Jill-Kitten** [comment]
Also note that the dependent library mods Puzzles & ForgeConfigApiPort do not cause the issue, with them installed and the EasyShulkerBoxes file removed I can get on Realms without issue, only when I include the fie for EasyShulkerBoxes does it cause this issue.

**Comment by Fuzss** [comment]
That is intentional. 

EasyShulkerBoxes makes changes to both sides of the game (client&server), just having the changes on one side causes undefined behaviors. There is no easy way to just disable a mod on the fly when you want to connect to a Realm.

Puzzles Lib and FCAP work since they are libraries designed to be optional on client&server as long as no mod requiring them on both sides is present.

I'd recommend setting up a separate profile in your launcher with client-only mods for when you want to play on Realms.
