### ISSUE TITLE
[Bug]: Duplication and Losing 

### ISSUE THREAD

**Issue by SockmanPro** [Fuzss/easyshulkerboxes#57]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21

### Mod Version(s) (Required)

1/21

### Minimal Setup (Required)

Yes

### Notes (Required)

Current behavior: When right clicking an item out of an ender chest, there is a chance that it will pick out something else instead. When you go to check in your ender chest again you will see that what you intended to take out has been deleted and what you did take out is also in the ender chest (duplication). ALTHOUGH once you leave and rejoin world it will fix itself most of the time with sometimes having the duplication still there. The deleted item always recovers (from what i know)
To my knowledge this is at random and can't consistently be reproduced.

### latest.log (Required)

.

**Comment by Fuzss** [comment]
That's a desync issue unfortunately. No items are actually being deleted or duplicated.
In the latest version relogging is no longer required to resync, but the core issue hasn't been solved yet unfortunately.

**Comment by Fuzss** [comment]
Should be fixed in the 1.21.1 version. Please reopen if not.
