### ISSUE TITLE
[Crash]: Game crashing after opening Inventory?

### ISSUE THREAD

**Issue by pewblaze** [Fuzss/easyshulkerboxes#6]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

EasyShulkerBoxes-v4.3.1-1.19.2-Fabric

### Notes (Required)

Im not sure. I fought against pillagers, picked up some coins from Numismatic Overhaul & wanted to put them in my purse (right click). Game crashed. (Im playing on a server)

### Crash Report (Required)

https://gist.github.com/pewblaze/8ae8e6002def9316e836bcd63994fc96

**Comment by Fuzss** [comment]
Same issue as this one: https://github.com/wisp-forest/numismatic-overhaul/issues/3
I'll have to see what I'll do about that.

**Comment by Fuzss** [comment]
Fixed in v4.3.2.
