### ISSUE TITLE
[Bug]: forgot to update this mod for 1.21.1?

### ISSUE THREAD

**Issue by VaporeonScripts** [Fuzss/easyshulkerboxes#61]
### Mod Loader (Required)

NeoForge

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

not needed

### Minimal Setup (Required)

Yes

### Notes (Required)

its the only mod that isnt updated to 1.21.1

### latest.log (Required)

a

**Comment by VaporeonScripts** [comment]
i know :/ just wondering why all mods got updated for 1.21.1 while this not, making me unable to update all mods to 1.21.1

**Comment by Fuzss** [comment]
Update is out now.
