### ISSUE TITLE
[Bug]: Item-deleting compatibilty issue with the Reinforced Shulker Boxes mod

### ISSUE THREAD

**Issue by Traehgniw** [Fuzss/easyshulkerboxes#8]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.18,2

### Mod Version (Required)

v3.1.1-1.18.2

### Notes (Required)

Some kind of compatibilty error with Reinforced Shulker Boxes.

Current behaviour: If you have a reinforced shulker box and put itin your inventory, you can add/remove items from the first 3 rows (the same number of slots as a vanilla shulker box) normally. However, if you have anything in the slots beyond that, inventory-interacting with the reinforced shulker deletes those items.

Expected behaviour: EITHER 
a. you can't inventory interact with reinforced shulker boxes 

OR

b. you can inventory interact with all the slots of a reinforced shulker box without it deleting your items.

Steps to reproduce:
1. Install both this mod and Reinforced Shulker Boxes.
2. Get a reinforced shulker box via /give, the creative menu, or crafting a shulker box with 8 copper ingots.
3. Put something in the slots beyond the 27th slot. You will need to put it down on the ground for this. (attempting to put in more than 27 distinct item stacks via the inventory will just fail)
4. Try and inventory interact with the reinforced shulker. (Note: If you have nothing in the first 27 slots, only putting stuff in will work. Trying to take stuff out doesn't do anything at all).
5. Set it back down and open it to observe that everything in slot 28 and onwards is gone.

**Comment by Traehgniw** [comment]
A little further testing: In order to delete your stuff the inventory interaction would have to be able to succeed if only the first 27 slots existed. If you, say, put 43 arrows in the first 43 distinct stacks in a copper shulker box and then try to right-click in a steak in your inventory, the steak doesn't go in despite there being two empty slots but the arrows all remain. Basically nothing happens at all. If you try to remove an arrow, though, or try to right click in an arrow, it does do the inventory interaction and deletes everything in slots over 27. Same for if you have one of the empty slots in the first 3 rows, instead of having them be the last 2 slots at the bottom.

**Comment by Fuzss** [comment]
Fixed in v4.3.4, only vanilla shulker boxes will work now. There is a new framework in place to support shulker boxes from other mods, but that needs to be enabled in-code. I'll look into this in the future, or maybe the other mod author can just enable it, we'll see.
