### ISSUE TITLE
[Bug]: Incompatibility with Enchanted Shulkers Mod

### ISSUE THREAD

**Issue by ColdPiano** [Fuzss/easyshulkerboxes#9]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.3.3

### Notes (Required)

Current Behaviour: If I utilise the easy-access features of this mod to right-click an item in or out of a shulker, the next time I place the shulker box on the ground, it will lose its enchantments from the Enchanted Shulkers Mod [v 1.0.2] (By RubixDev). The shulker will not lose its enchantments until placed down, and will also not lose its enchantments if placed down and picked up without having right-clicked an item in or out of it via Easy Shulker Boxes.
Steps to reproduce:
1. Possess an enchanted shulker box using the mod mentioned above. 
2. Right-click an item in or out of it (functions normally and does not impact enchants yet)
3. place box and pick back up using pickaxe

Result: enchantments will be wiped from box

**Comment by Fuzss** [comment]
Fixed in v4.3.4.
